NUMPY PART - 4

In [1]:
#Sort, Search & Counting function.

In [2]:
import numpy as np

In [6]:
arr = np.array([12,13,445,1,2,3,4,5,67,8,9,10])

In [7]:
arr

array([ 12,  13, 445,   1,   2,   3,   4,   5,  67,   8,   9,  10])

In [8]:
np.sort(arr)

array([  1,   2,   3,   4,   5,   8,   9,  10,  12,  13,  67, 445])

In [11]:
np.searchsorted(arr , 34 )

12

In [12]:
arr1 = np.array([0,345,454,0,0,0,0,0])

In [13]:
np.count_nonzero(arr1)

2

In [14]:
arr

array([ 12,  13, 445,   1,   2,   3,   4,   5,  67,   8,   9,  10])

In [16]:
np.where(arr > 6 )

(array([ 0,  1,  2,  8,  9, 10, 11]),)

In [17]:
np.extract(arr>6 , arr)

array([ 12,  13, 445,  67,   8,   9,  10])

In [18]:
#Numpy - Byte Swapping

In [19]:
arr

array([ 12,  13, 445,   1,   2,   3,   4,   5,  67,   8,   9,  10])

In [20]:
arr.byteswap()

array([  864691128455135232,   936748722493063168, -4827577325564461056,
          72057594037927936,   144115188075855872,   216172782113783808,
         288230376151711744,   360287970189639680,  4827858800541171712,
         576460752303423488,   648518346341351424,   720575940379279360])

In [21]:
a = np.copy(arr)

In [22]:
b = arr.view()

In [23]:
b

array([ 12,  13, 445,   1,   2,   3,   4,   5,  67,   8,   9,  10])

In [24]:
arr

array([ 12,  13, 445,   1,   2,   3,   4,   5,  67,   8,   9,  10])

In [25]:
a = np.copy(arr)

In [26]:
b = arr.view()

In [27]:
b

array([ 12,  13, 445,   1,   2,   3,   4,   5,  67,   8,   9,  10])

In [28]:
#Numpy - Matrix Library

In [29]:
import numpy.matlib as nm

In [30]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [31]:
nm.ones((3,4
        ))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [32]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
# Numpy - Linear Algebra 

In [34]:
arr1 = np.random.randint([[2,3], [4,5]])

In [35]:
arr2 = np.random.randint([[2,3], [4,5]])

In [36]:
np.dot(arr1,arr2)

array([[5, 2],
       [4, 0]])

In [37]:
arr1@arr2

array([[5, 2],
       [4, 0]])