NUMPY PART - 2

In [4]:
#Numpy - Array manipulation.

In [2]:
import numpy as np

In [5]:
arr = np.random.randint(1,10 , (3,4))

In [6]:
arr

array([[6, 9, 3, 7],
       [5, 1, 3, 4],
       [9, 6, 5, 7]])

In [7]:
arr.reshape(6,2)

array([[6, 9],
       [3, 7],
       [5, 1],
       [3, 4],
       [9, 6],
       [5, 7]])

In [8]:
arr.reshape(2,6)

array([[6, 9, 3, 7, 5, 1],
       [3, 4, 9, 6, 5, 7]])

In [11]:
arr.reshape(2,-234)

array([[6, 9, 3, 7, 5, 1],
       [3, 4, 9, 6, 5, 7]])

In [12]:
arr.T

array([[6, 5, 9],
       [9, 1, 6],
       [3, 3, 5],
       [7, 4, 7]])

In [13]:
arr

array([[6, 9, 3, 7],
       [5, 1, 3, 4],
       [9, 6, 5, 7]])

In [14]:
arr.flatten()

array([6, 9, 3, 7, 5, 1, 3, 4, 9, 6, 5, 7])

In [16]:
arr1 = np.array([1,2,3,3,4])

# 

In [17]:
arr1.ndim

1

In [18]:
np.expand_dims(arr1 ,axis=1)

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [19]:
np.expand_dims(arr1 , axis=0)

array([[1, 2, 3, 3, 4]])

In [20]:
np.squeeze(arr)

array([[6, 9, 3, 7],
       [5, 1, 3, 4],
       [9, 6, 5, 7]])

In [21]:
data = np.array([[1], [2], [3]])

In [22]:
data

array([[1],
       [2],
       [3]])

In [23]:
np.squeeze(data)

array([1, 2, 3])

In [24]:
arr1

array([1, 2, 3, 3, 4])

In [25]:
np.repeat(arr1 , 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [26]:
np.roll(arr1 ,2)

array([3, 4, 1, 2, 3])

In [27]:
arr1

array([1, 2, 3, 3, 4])

In [28]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [29]:
#Numpy - Binary Operators

In [30]:
arr1 = np.random.randint(1,10 , (3,4))

In [31]:
arr2 = np.random.randint(1,10 , (3,4))

In [32]:
arr1

array([[7, 3, 2, 9],
       [8, 3, 4, 5],
       [4, 5, 1, 9]])

In [33]:
arr2

array([[1, 4, 7, 1],
       [4, 5, 4, 3],
       [8, 5, 5, 9]])

In [34]:
arr1+arr2

array([[ 8,  7,  9, 10],
       [12,  8,  8,  8],
       [12, 10,  6, 18]])

In [35]:
arr1*arr2

array([[ 7, 12, 14,  9],
       [32, 15, 16, 15],
       [32, 25,  5, 81]])

In [36]:
arr1/arr2

array([[7.        , 0.75      , 0.28571429, 9.        ],
       [2.        , 0.6       , 1.        , 1.66666667],
       [0.5       , 1.        , 0.2       , 1.        ]])

In [37]:
arr1-arr2

array([[ 6, -1, -5,  8],
       [ 4, -2,  0,  2],
       [-4,  0, -4,  0]])

In [38]:
arr1%arr2

array([[0, 3, 2, 0],
       [0, 3, 0, 2],
       [4, 0, 1, 0]])

In [40]:
arr1 ** arr2

array([[        7,        81,       128,         9],
       [     4096,       243,       256,       125],
       [    65536,      3125,         1, 387420489]])

In [42]:
arr1 & arr2

array([[1, 0, 2, 1],
       [0, 1, 4, 1],
       [0, 5, 1, 9]])

In [45]:

arr2

array([[1, 4, 7, 1],
       [4, 5, 4, 3],
       [8, 5, 5, 9]])

In [47]:
-arr1                   #Negate operation

array([[-7, -3, -2, -9],
       [-8, -3, -4, -5],
       [-4, -5, -1, -9]])

In [48]:
arr1>arr2

array([[ True, False, False,  True],
       [ True, False, False,  True],
       [False, False, False, False]])

In [49]:
#Numpy - String Function.

In [50]:
np.array(['subh', 'kumar' , ])

array(['subh', 'kumar'], dtype='<U5')

In [51]:
arr

array([[6, 9, 3, 7],
       [5, 1, 3, 4],
       [9, 6, 5, 7]])

In [59]:
#Numpy  Mathematical Function.

In [60]:
arr1

array([[7, 3, 2, 9],
       [8, 3, 4, 5],
       [4, 5, 1, 9]])

In [61]:
np.sin(arr1)

array([[ 0.6569866 ,  0.14112001,  0.90929743,  0.41211849],
       [ 0.98935825,  0.14112001, -0.7568025 , -0.95892427],
       [-0.7568025 , -0.95892427,  0.84147098,  0.41211849]])

In [62]:
np.tan(arr1)

array([[ 0.87144798, -0.14254654, -2.18503986, -0.45231566],
       [-6.79971146, -0.14254654,  1.15782128, -3.38051501],
       [ 1.15782128, -3.38051501,  1.55740772, -0.45231566]])

In [63]:
np.tanh(arr1)

array([[0.99999834, 0.99505475, 0.96402758, 0.99999997],
       [0.99999977, 0.99505475, 0.9993293 , 0.9999092 ],
       [0.9993293 , 0.9999092 , 0.76159416, 0.99999997]])

In [64]:
np.log10(arr1)

array([[0.84509804, 0.47712125, 0.30103   , 0.95424251],
       [0.90308999, 0.47712125, 0.60205999, 0.69897   ],
       [0.60205999, 0.69897   , 0.        , 0.95424251]])

In [65]:
np.exp(arr1)

array([[1.09663316e+03, 2.00855369e+01, 7.38905610e+00, 8.10308393e+03],
       [2.98095799e+03, 2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [5.45981500e+01, 1.48413159e+02, 2.71828183e+00, 8.10308393e+03]])

In [66]:
np.sqrt(arr1)

array([[2.64575131, 1.73205081, 1.41421356, 3.        ],
       [2.82842712, 1.73205081, 2.        , 2.23606798],
       [2.        , 2.23606798, 1.        , 3.        ]])

In [67]:
np.power(arr1,2)

array([[49,  9,  4, 81],
       [64,  9, 16, 25],
       [16, 25,  1, 81]])

In [68]:
np.mean(arr1)

5.0

In [70]:
np.median(arr1)

4.5

In [71]:
np.std(arr1)

2.581988897471611

In [72]:
np.var(arr1)

6.666666666666667

In [73]:
np.min(arr1)

1

In [75]:
np.max(arr1)

9